server:
  port: 8080
  servlet:
    context-path: /restaurantserver

spring:
  config:
    import: optional:file:./application.env
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/restaurantserver/login/oauth2/code/google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  main:
    allow-bean-definition-overriding: true

  data:
    redis:
      host: localhost
      port: 6379

cloudinary:
  cloud_name: ${CLOUDINARY_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: ${JWT_ISSUER}

vnpay:
  tmnCode: ${VNPAY_TMN_CODE}
  secretKey: ${VNPAY_SECRET_KEY}
  baseUrl: ${VNPAY_BASE_URL}
  returnUrl: ${VNPAY_RETURN_URL}

redis:
  stream-key: kitchen-stream
  zset-key: kitchen-priority-queue
  stream:
    group: bep_group
    consumer: bep_1
stripe:
  key:
    public: ${STRIPE_PUBLISH_KEY}
    secret: ${STRIPE_SECRET_KEY}
webhook:
  key: ${WEBHOOK_KEY}
app:
  firebase:
    config: ${FIREBASE_CONFIG_PATH}

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: TRACE